 ---
title: "BIO201 final presentation"
author: Kasey Neff
date: 11.18.19
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/Documents/Bio201_Project/Kasey/")
```

## R Markdown

```{r Load packages, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE, results='hide'}
library(tidyverse)
library(readxl)
library(broom)
library(cowplot)
library(phyloseq)
library(agricolae)
set.seed(7)

 scfa_weekly <- SCFA_wkly %>% 
  rename_all(tolower) %>% 
  filter(quantity_compliant == "yes", study_week == "week1" | study_week == "week3") %>% 
  select(-starts_with("ace"), -starts_with("but"), -ends_with("median")) %>% 
  spread(study_week, propionate_mean)
 
Accessible_weekly <- scfa_weekly %>%
   filter(!is.na(supplement_consumed)) %>%
   filter (supplement_consumed == "Accessible")

BRMPS_Accessible_weekly <- scfa_weekly %>%
   filter(!is.na(supplement_consumed)) %>%
   filter (supplement_consumed == "BRMPS+Accessible")

BRMPS_weekly <- scfa_weekly %>%
   filter(!is.na(supplement_consumed)) %>%
   filter (supplement_consumed == "BRMPS")

Arabino_weekly <- scfa_weekly %>%
   filter(!is.na(supplement_consumed)) %>%
   filter (supplement_consumed == "Arabino")

HiMaize_weekly <- scfa_weekly %>%
   filter(!is.na(supplement_consumed)) %>%
   filter(supplement_consumed == "HiMaize")
#created data frame for each of the assigned supplements  (each member had four supplements, HiMaize was found to be significant)
```

## Assumptions & T Test (or wilcoxon) for Accessible, Arabino, BRMPS, BRMPS+Accessible, & HiMaize (added once we found out it was the significant supplement)

```{r}
# sample size of each group
scfa_weekly %>% 
  filter(supplement_consumed == "Accessible") %>% 
  summarize(sample_size = n()) # week1 n=31 & week3 n=32, not use the NA 
scfa_weekly %>% 
  filter(supplement_consumed == "Arabino") %>% 
  summarize(sample_size = n()) # week1 n=17 & week3 n=13, not use the NA -> WILCOXON
scfa_weekly %>% 
  filter(supplement_consumed == "BRMPS") %>% 
  summarize(sample_size = n()) # week1 n=151 & week3 n=151, not use the NA 
scfa_weekly %>% 
  filter(supplement_consumed == "BRMPS+Accessible") %>% 
  summarize(sample_size = n()) # week1 n=17 & week3 n=16, not use the NA -> WILCOXON

# check normality of each group
shapiro.test(Accessible_weekly$week1) 
ggplot(Accessible_weekly, aes(x = week1)) + geom_histogram() # p=0.001208, skewed to the right -> not normal 
shapiro.test(Accessible_weekly$week3) 
ggplot(Accessible_weekly, aes(x = week3)) + geom_histogram() #p=0.0006834, skewed to the right -> not normal

shapiro.test(Arabino_weekly$week1) 
ggplot(Arabino_weekly, aes(x = week1)) + geom_histogram() # p=0.01328, skewed to the right -> not normal 
shapiro.test(Arabino_weekly$week3) 
ggplot(Arabino_weekly, aes(x = week3)) + geom_histogram() # p=  0.5143, sort of normal shaped -> normal

shapiro.test(BRMPS_weekly$week1) 
ggplot(BRMPS_weekly, aes(x = week1)) + geom_histogram() # p=6.225e-06, bimodal and skewed to the right -> not normal
shapiro.test(BRMPS_weekly$week3) 
ggplot(BRMPS_weekly, aes(x = week3)) + geom_histogram() # p=1.357e-09, skewed to the right -> not normal

shapiro.test(BRMPS_Accessible_weekly$week1) 
ggplot(BRMPS_Accessible_weekly, aes(x = week1)) + geom_histogram() # p=0.202, sort of bimodal and very spread out
shapiro.test(BRMPS_Accessible_weekly$week3) 
ggplot(BRMPS_Accessible_weekly, aes(x = week3)) + geom_histogram() # p=0.02685, skewed to the right -> not normal

# check variances
var.test(x = Accessible_weekly$week1, 
         y = Accessible_weekly$week3, 
         alternative = "two.sided") # p=0.2249, variances are not equal
var.test(x = Arabino_weekly$week1, 
         y = Arabino_weekly$week3, 
         alternative = "two.sided") # p=0.6808, variances are equal
var.test(x = BRMPS_Accessible_weekly$week1, 
         y = BRMPS_Accessible_weekly$week3, 
         alternative = "two.sided") # p=0.9149, variances are equal
var.test(x = BRMPS_weekly$week1, 
         y = BRMPS_weekly$week3, 
         alternative = "two.sided") # p=0.01992, variances are not equal

# run the wilcox
BRMPS_Accessible_weekly <- na.omit(BRMPS_Accessible_weekly) 
wilcox.test(x = BRMPS_Accessible_weekly$week1, 
            y = BRMPS_Accessible_weekly$week3, 
            alternative = "less", paired = TRUE, var.equal = TRUE)

#the p value for the wilcox is 0.45, which is not less than 0.05 and fails to reject the null. The propionate concentration for week 1 and week 3 are the same.

BRMPS_weekly <- na.omit(BRMPS_weekly) 
wilcox.test(x = BRMPS_weekly$week1, 
            y = BRMPS_weekly$week3, 
            alternative = "less", paired = TRUE, var.equal = TRUE)

#the p value for the wilcox is 0.8386, which is larger than 0.05 and fails to reject the null. The propionate concentration for week 1 and week 3 are the same.

Accessible_weekly <- na.omit(Accessible_weekly) 
wilcox.test(x = Accessible_weekly$week1, 
            y = Accessible_weekly$week3, 
            alternative = "less", paired = TRUE, var.equal = TRUE)

#the p value for the wilcox is 0.1258, which is larger than 0.05 and fails to reject the null. The propionate concentration for week 1 and week 3 are the same.

Arabino_weekly <- na.omit(Arabino_weekly) 
wilcox.test(x = Arabino_weekly$week1, 
            y = Arabino_weekly$week3, 
            alternative = "less", paired = TRUE, var.equal = TRUE)

#the p value for the wilcox is 0.0874, which is larger than 0.05 and fails to reject the null. The propionate concentration for week 1 and week 3 are the same.
#None of my supplements were significant even with the wilcoxon test. 

HiMaize_weekly <- na.omit(HiMaize_weekly) 
wilcox.test(x = HiMaize_weekly$week1, 
            y = HiMaize_weekly$week3, 
            alternative = "less", paired = TRUE, var.equal = TRUE)

#The p value for the wilcox is 0.01215, which is less than 0.05 and thus rejects the null that the propionate concentration for week 1 and week 3 are not the same. HiMaize is the only significant supplement.
```

#Ordinated plot and propionate phyloseq

```{r}
# sample data 
read_delim("~/Documents/Bio201_Project/Yilin/curated_data/long_priop_delta.txt", 
                            delim = "\t", escape_double = FALSE, 
                            trim_ws = TRUE, 
                            col_types = cols()) 

long_priop_delta_table <- long_priop_delta %>%  
  mutate(sample_id = paste(participant_id, study_week, sep="_")) %>%
  column_to_rownames(var = "sample_id") %>% 
  sample_data(.) 

# seq var info 
all_data_indv <- read_delim("~/Documents/Bio201_Project/final_project_data/species_avg_shared.txt", 
                            delim = "\t", escape_double = FALSE, 
                            trim_ws = TRUE, 
                            col_types = cols()) %>%
  rename_all(tolower) %>% 
  filter(semester == "Winter2017" | semester == "Fall2015") %>%
  select(-semester) %>% 
  mutate(sample_id = paste(participant_id, study_week, sep="_")) %>% 
  distinct(., sample_id, .keep_all = TRUE) %>% 
  column_to_rownames(var = "sample_id") %>% 
  select(-participant_id, -study_week) %>%
  as.matrix() %>% 
  otu_table(., taxa_are_rows = FALSE) 

# merge all three data frames into phyloseq obj
physq_obj <- phyloseq(all_data_indv, long_priop_delta_table) 
physq_obj 

# ordination plot
physq_bc <- ordinate(physq_obj, 
                      method = "NMDS", 
                      k=2, maxit=100, try=50,
                      distance = "bray")

ordplot1 <- plot_ordination(physeq = physq_obj, 
                     ordination = physq_bc, 
                     type = "samples", 
                     color = "study_week", 
                     shape = "study_week") %>% 
  plot(main = "Ordination Plot of Study Week & Semester Data")
ordplot1 

ordplot2 <- ordplot1 +
  geom_point(size=2) + 
  scale_color_manual(name = "Study week",
                     values = c("coral3", 
                                "skyblue3"),
                     labels = c("week1", "week3")) +
  scale_shape_manual(name = "Study week",
                     values = c(7, 8),
                     labels = c("week1", "week3"))
ordplot2 

save_plot(filename = "ordplot2.pdf",
          plot = ordplot2,
          nrow = 1, ncol = 2, 
          base_aspect_ratio = 1.1)
save_plot(filename = "ordplot1.pdf",
          plot = ordplot1,
          nrow = 1, ncol = 2, 
          base_aspect_ratio = 1.1)
```
```{r}
#violin plot = to check whether or not the proprionate levels changed from week1 to week3, and to check how different the two semesters were. The two semesters looked very different, which could explain why our data looks very random and we found no correlelation. Each semester contains very different microbiomes, all that change in different ways in response to the supplement. 
priop_violin <- long_priop_delta %>%
  filter(study_week == "week1" | study_week == "week3") %>% 
  ggplot(aes(x = study_week, 
             y = proprionate_value,
             color = study_week)) + 
  geom_violin()
print(priop_violin)

priop_violin2 <- long_priop_delta %>%
  filter(semester == "Fall2015" | semester == "Winter2017") %>% 
  ggplot(aes(x = semester, 
             y = proprionate_value,
             color = semester)) + 
  geom_violin()
print(priop_violin2)
  
save_plot(filename = "priop_violin.pdf",
          plot = priop_violin,
          nrow = 1, ncol = 2, 
          base_aspect_ratio = 1.1)
save_plot(filename = "priop_violin2.pdf",
          plot = priop_violin2,
          nrow = 1, ncol = 2, 
          base_aspect_ratio = 1.1)
          
          
read_delim("~/Documents/Bio201_Project/final_project_data/phylum_avg_shared.txt", 
                            delim = "\t", escape_double = FALSE, 
                            trim_ws = TRUE, 
                            col_types = cols()) 

#Bar plot to show the different bacterial compositions of the two semesters
phylum_data <- phylum_avg_shared %>% 
  rename_all(tolower) %>% 
  filter(study_week == "week1" | study_week == "week3",
         semester == "Fall2015" | semester == "Winter2017") %>%
  mutate(sample_id = paste(participant_id, study_week, sep = "_")) %>%
  select(-participant_id, -study_week, -semester) %>%
  column_to_rownames(var = "sample_id") %>%
  as.matrix() %>% #convert data frame to matrix object
  otu_table(., taxa_are_rows = FALSE) #specify type of phyloseq object

scfa_weekly_wide <- SCFA_wkly %>% 
  rename_all(tolower) %>% 
  filter(quantity_compliant == "yes", study_week == "week1" | study_week == "week3") %>% 
  select(-starts_with("ace"), -starts_with("but"), -ends_with("median"))

HiMaize_weekly_wide <- scfa_weekly_wide %>% 
  filter(!is.na(supplement_consumed)) %>%
  filter(supplement_consumed == "HiMaize") %>% 
  mutate(sample_id = paste(participant_id, study_week, sep = "_")) %>% 
  column_to_rownames(var = "sample_id") %>%
  sample_data(.)
  
physq_phylum_obj <- phyloseq(phylum_data, HiMaize_weekly_wide) 
physq_phylum_obj 

physq_long <- physq_phylum_obj %>%
  transform_sample_counts(function(x) {x/sum(x)} ) %>% #calculate rel abund
  psmelt() %>%
  rename_all(tolower)

phylum_plot <- ggplot(data = physq_long, 
       aes(x = study_week, #specify the arguments for each axis
           y = abundance, 
           fill = otu)) + #set fill to the taxa rank
  geom_col() + #plot type for bars 
  facet_grid(~semester) + #panel for each semester
  xlab(NULL) + 
  theme(axis.text.x = element_text(angle = 90,
                                   vjust = 0.5)) + #clean up x-axis labels 
  ylab("Relative Abundance (Phyla > 0.1%)") 
phylum_plot

save_plot(filename = "phylum_plot.pdf",
          plot = phylum_plot,
          nrow = 1, ncol = 1, 
          base_aspect_ratio = 3)

```